[project]
name = 'Quantum-Computing-Resource-Sharing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.job-submission]
path = 'contracts/job-submission.clar'
clarity_version = 2
epoch = 2.5

[contracts.resource-allocation]
path = 'contracts/resource-allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.result-verification]
path = 'contracts/result-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
